-- 1. Таблица users
CREATE TABLE users (
	user_name VARCHAR(255) PRIMARY KEY,
    parol TEXT NOT NULL
);

-- 2. Таблица scope_info 
-- (согласно спецификации объединяет поля scope и hash_info)
CREATE TABLE scope_info (
    scope_name VARCHAR(255) PRIMARY KEY,
    scope_json_meta JSONB,
    hash_salt TEXT,
    hash_type TEXT,
    hash_json_meta JSONB
);

-- 3. Таблица commit
-- Имя взято в кавычки, т.к. COMMIT — зарезервированное слово SQL
CREATE TABLE "commit_ver" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commit_time TIMESTAMP,
    json_meta JSONB,
    author_fk VARCHAR(255) REFERENCES users(user_name),
    scope_fk VARCHAR(255) REFERENCES scope_info(scope_name)
);

-- 4. Таблица eval_res
-- Составной PK согласно спецификации: (eval res/name, scope fk)
CREATE TABLE eval_res (
    eval_name VARCHAR(255) NOT NULL,
    scope_fk VARCHAR(255) NOT NULL REFERENCES scope_info(scope_name),
    json_data JSONB,
    commit_fk BIGINT REFERENCES "commit_ver"(id),
    PRIMARY KEY (eval_name, scope_fk)
);

-- 5. Таблица nodes
CREATE TABLE nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- hash TEXT, пока не нужен
    type TEXT,
    display_text TEXT,
    json_meta JSONB,
    create_time TIMESTAMP,
    delete_time TIMESTAMP,
    scope_fk VARCHAR(255) REFERENCES scope_info(scope_name),
    last_commit_fk BIGINT REFERENCES "commit_ver"(id)
);
-- 5.1 hash to node
CREATE TABLE hash_to_nodes(
    hash TEXT,
    hash_type TEXT,
	scope_fk VARCHAR(255) NOT NULL REFERENCES scope_info(scope_name),
    node_fk BIGINT NOT NULL REFERENCES nodes(id),
    PRIMARY KEY (hash, hash_type,scope_fk)
);

-- 6. Таблица rels
-- Составной PK: (rel/id, left node fk, right node fk)
CREATE TABLE rels (
    rel_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    left_node_fk BIGINT NOT NULL REFERENCES nodes(id),
    right_node_fk BIGINT NOT NULL REFERENCES nodes(id),
    hash TEXT,
    type TEXT,
    json_meta JSONB,
    display_text TEXT,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    last_commit_fk BIGINT REFERENCES "commit_ver"(id),
    PRIMARY KEY (rel_id, left_node_fk, right_node_fk)
);
-- 7. Таблица rels by hash
CREATE TABLE hash_to_rels(
    hash TEXT,
    hash_type TEXT,
    scope_fk VARCHAR(255) NOT NULL REFERENCES scope_info(scope_name),
    rel_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    left_node_fk BIGINT NOT NULL REFERENCES nodes(id),
    right_node_fk BIGINT NOT NULL REFERENCES nodes(id),
    PRIMARY KEY (hash, hash_type, scope_fk, left_node_fk, right_node_fk),
    FOREIGN KEY (rel_id, left_node_fk, right_node_fk) 
    	REFERENCES rels(rel_id, left_node_fk, right_node_fk) ON DELETE CASCADE
);
